name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-stable

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-stable
      
      - name: Install packages needed for GLFW
        run: |
          sudo apt update
          sudo apt install -y  build-essential libalut-dev libasound2-dev libc6-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev mesa-utils pkg-config xorg-dev xvfb
      - name: Build Nimdustry
        run: |
          nimble build -Y
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v7
      - name: Verify Emscripten is installed
        run: emcc -v
      - name: Build web version
        run: |
          git config --global user.email "cli@github.com"
          git config --global user.name "Github Actions"
          nimble install nake -Y
          nake web
          git checkout gh-pages
          rm index*
          cp build/web/* .
          rm -rf build/ assets/ fuse/
          git add .
          git commit -m "Updating pages"
          git push https://Anuken:${{ secrets.API_TOKEN_GITHUB }}@github.com/Anuken/nimdustry
          
